test:
	./decrypt jJAZKTtoHkl6/S+cps1kDOiRB/kggs/+7le4ESsLRCwznt2/hbuWA4Bgd/Y8jd1sVJyc0qZEPZmIIWwKfsNjBw==

ugster: 
	scp * a3savin@ugster21.student.cs.uwaterloo.ca:~/a3

tar:
	tar cvf src.tar *.rb decrypt encrypt

submit:
	scp src.tar a3savin@linux.student.cs.uwaterloo.ca:~/cs458/a3
