test:
	./decrypt MyIRPiUsdscsstIMXjmLSfPbSwwcAdy/9mk/1xndYc+//Huw7T92LtOzDMuqF8q/6SyMveVnw/2uec+kpilnGA== 

#
#test_key:
#	./decrypt MyIRPiUsdscsstIMXjmLSfPbSwwcAdy/9mk/1xndYc+//Huw7T92LtOzDMuqF8q/6SyMveVnw/2uec+kpilnGA== 1234567890ABCDEF
#

