sploit1:
	gcc -Wall -ggdb sploit1.c -o sploit1

sploit2:
	gcc -Wall -ggdb sploit2.c -o sploit2

sploit3:
	gcc -Wall -ggdb sploit3.c -o sploit3

sploit4:
	gcc -Wall -ggdb sploit4.c -o sploit4

send:
	scp * a3savin@ugster21.student.cs.uwaterloo.ca:~/uml/share/

submit:
	scp sploit*.c *.pdf a3savin@linux.student.cs.uwaterloo.ca:/u4/a3savin/cs458/
